package com.quest.solution.ui;

import com.quest.solution.ui.action.StartGame;
import com.quest.solution.ui.wrapper.ItemWrapper;
import com.quest.solution.ui.wrapper.LocationWrapper;
import com.quest.solution.ui.wrapper.NPCWrapper;
import com.quest.solution.ui.wrapper.PlayerWrapper;
import com.quest.solutions.run.db.entity.events.ResponseEventType;
import com.quest.solutions.run.logic.analyzer.FrontGameController;
import com.quest.solutions.run.logic.analyzer.ResultProxyText;
import javax.swing.JOptionPane;

/**
 *
 * @author arle0814
 */
public class GameUI extends javax.swing.JFrame {

    private static final String SEPARATOR = " ";

    private FrontGameController gController;
    private LocationWrapper locationWrapper;
    private PlayerWrapper playerWrapper;

    /**
     * Creates new form GameUI
     */
    public GameUI() {
        initComponents();
    }

    private void configureComponents(boolean enable) {
        jCommandComboBox.setEnabled(enable);
        jCommandTextField.setEnabled(enable);
        jExecuteButton.setEnabled(enable);
        jInventoryButton.setEnabled(enable);
        jHelpButton.setEnabled(enable);
    }

    private void setNavigationInfo() {
        jLocationDescriptionTextArea.setText(this.locationWrapper.getCurrentNameLocation() + " " + this.locationWrapper.getDesciptionCurrentLocation());

        jImageLocationLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(this.locationWrapper.getImageLocation())));
        if (this.locationWrapper.getStreets() != null && !this.locationWrapper.getStreets().isEmpty()) {
            jStreetsList.setListData(this.locationWrapper.getStreets().toArray());
        } else {
            jStreetsList.setListData(new String[]{});
        }
        if (this.locationWrapper.getRooms() != null && !this.locationWrapper.getRooms().isEmpty()) {
            jRoomsList.setListData(this.locationWrapper.getRooms().toArray());
        } else {
            jRoomsList.setListData(new String[]{});
        }
    }

    private void setItemInfo() {
        jItemInvetoryInLocList.setListData(this.locationWrapper.getItemInLocation().values().toArray());
    }

    private void setMonsterInfo() {
        jMonsterList.setListData(this.locationWrapper.getMonstersInLocation().values().toArray());
    }

    private void setNPCInfo() {
        jPeopleList.setListData(this.locationWrapper.getNpcInLocation().values().toArray());
    }

    private void setPlayerInfo() {
        jInventoryPlayerList.setListData(this.playerWrapper.getItems().values().toArray());
        jPlayerNameTextField.setText(this.playerWrapper.getName());
        jHealthProgressBar.setValue(this.playerWrapper.getHealth());
        jMentalStateProgressBar.setValue(this.playerWrapper.getMentalState());
        jImagePlayerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(this.playerWrapper.getImage())));
    }

    private void initAllData() {
        this.locationWrapper = new LocationWrapper(this.gController.getGameContext().getGameNavigation().getCurrentLocation(),
                this.gController.getGameContext().getGameNavigation().getStreetLocation(),
                this.gController.getGameContext().getGameNavigation().getRoomLocation());
        this.playerWrapper = new PlayerWrapper(this.gController.getGameContext().getPlayer());
        this.setNavigationInfo();
        this.setItemInfo();
        this.setMonsterInfo();
        this.setNPCInfo();
        this.setPlayerInfo();
    }

    private void setStartEvent() {
        this.gController.setProxyText(new ResultProxyText("", ResponseEventType.WINDOW,
                this.gController.getGameContext().getLoadEventDescription()));
    }

    private void startGame() {
        this.configureComponents(true);
        this.gController = new StartGame().execute();
        this.initAllData();
        this.setStartEvent();
        this.checkEvent();
    }

    private void checkEvent() {
        if (this.gController.getProxyText() != null && this.gController.getProxyText().getTypeEvent() == ResponseEventType.WINDOW) {
            JOptionPane.showMessageDialog(this,
                    this.gController.getProxyText().getTextPopup());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInventoryDialog = new javax.swing.JDialog();
        jPlayerPanel = new javax.swing.JPanel();
        jNameLabel = new javax.swing.JLabel();
        jHealthLabel = new javax.swing.JLabel();
        jMStateLabel = new javax.swing.JLabel();
        jPlayerNameTextField = new javax.swing.JTextField();
        jPlayerInfoFullLabel1 = new javax.swing.JLabel();
        jImagePlayerLabel = new javax.swing.JLabel();
        jHealthProgressBar = new javax.swing.JProgressBar();
        jMentalStateProgressBar = new javax.swing.JProgressBar();
        jScrollPane3 = new javax.swing.JScrollPane();
        jInventoryPlayerList = new javax.swing.JList();
        jItemInventoryLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaItemDescription = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabelImageItem = new javax.swing.JLabel();
        jButtonSelectItemInventory = new javax.swing.JButton();
        jPanelExecute = new javax.swing.JPanel();
        jCommandComboBox = new javax.swing.JComboBox();
        jExecuteButton = new javax.swing.JButton();
        jCommandTextField = new javax.swing.JTextField();
        jCommandLabel = new javax.swing.JLabel();
        jNavigationPanel = new javax.swing.JPanel();
        jStreetsPanel = new javax.swing.JPanel();
        jStreetsScrollPane = new javax.swing.JScrollPane();
        jStreetsList = new javax.swing.JList();
        jLabelStreets = new javax.swing.JLabel();
        jPanelRooms = new javax.swing.JPanel();
        jLabelRooms = new javax.swing.JLabel();
        jRoomsScrollPane = new javax.swing.JScrollPane();
        jRoomsList = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jItemInvetoryInLocList = new javax.swing.JList();
        jItemsLabel = new javax.swing.JLabel();
        jNPCPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jMonsterList = new javax.swing.JList();
        jPlayerInfoFullLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPeopleList = new javax.swing.JList();
        jPlayerInfoFullLabel2 = new javax.swing.JLabel();
        jResultPanel = new javax.swing.JPanel();
        jResultLabel = new javax.swing.JLabel();
        jResultTextField = new javax.swing.JTextField();
        jTurnLabel = new javax.swing.JLabel();
        jTurnTextField = new javax.swing.JTextField();
        jLocationInfoPanel = new javax.swing.JPanel();
        jLocationInfoScrollPane = new javax.swing.JScrollPane();
        jLocationDescriptionTextArea = new javax.swing.JTextArea();
        jImageLocationLabel = new javax.swing.JLabel();
        jInventoryButton = new javax.swing.JButton();
        jHelpButton = new javax.swing.JButton();
        jGameMenuBar = new javax.swing.JMenuBar();
        GameJMenu = new javax.swing.JMenu();
        jStartMenuItem = new javax.swing.JMenuItem();
        jStatsMenuItem = new javax.swing.JMenuItem();
        jExitMenuItem = new javax.swing.JMenuItem();

        jInventoryDialog.setTitle("Player Inventory");
        jInventoryDialog.setLocationByPlatform(true);
        jInventoryDialog.setMinimumSize(new java.awt.Dimension(720, 450));

        jPlayerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jNameLabel.setText("Name:");

        jHealthLabel.setText("Health:");

        jMStateLabel.setText("Mental State:");

        jPlayerNameTextField.setEnabled(false);

        jPlayerInfoFullLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPlayerInfoFullLabel1.setText("Game Player:");

        jHealthProgressBar.setMaximum(5);

        jMentalStateProgressBar.setMaximum(5);

        javax.swing.GroupLayout jPlayerPanelLayout = new javax.swing.GroupLayout(jPlayerPanel);
        jPlayerPanel.setLayout(jPlayerPanelLayout);
        jPlayerPanelLayout.setHorizontalGroup(
            jPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPlayerPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jImagePlayerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPlayerPanelLayout.createSequentialGroup()
                        .addGroup(jPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jHealthLabel)
                            .addComponent(jMStateLabel)
                            .addComponent(jNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPlayerNameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jHealthProgressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMentalStateProgressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPlayerPanelLayout.createSequentialGroup()
                        .addComponent(jPlayerInfoFullLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPlayerPanelLayout.setVerticalGroup(
            jPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPlayerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPlayerInfoFullLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jImagePlayerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPlayerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNameLabel))
                .addGap(18, 18, 18)
                .addGroup(jPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jHealthLabel)
                    .addComponent(jHealthProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMStateLabel)
                    .addComponent(jMentalStateProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jInventoryPlayerList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jInventoryPlayerListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jInventoryPlayerList);

        jItemInventoryLabel.setText("Items:");

        jTextAreaItemDescription.setColumns(20);
        jTextAreaItemDescription.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextAreaItemDescription.setLineWrap(true);
        jTextAreaItemDescription.setRows(5);
        jTextAreaItemDescription.setEnabled(false);
        jScrollPane2.setViewportView(jTextAreaItemDescription);

        jLabel1.setText("Item Description:");

        jButtonSelectItemInventory.setText("Select");
        jButtonSelectItemInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectItemInventoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInventoryDialogLayout = new javax.swing.GroupLayout(jInventoryDialog.getContentPane());
        jInventoryDialog.getContentPane().setLayout(jInventoryDialogLayout);
        jInventoryDialogLayout.setHorizontalGroup(
            jInventoryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInventoryDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPlayerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jInventoryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInventoryDialogLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jInventoryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jItemInventoryLabel)))
                    .addGroup(jInventoryDialogLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabelImageItem, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jInventoryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addGroup(jInventoryDialogLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonSelectItemInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jInventoryDialogLayout.setVerticalGroup(
            jInventoryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInventoryDialogLayout.createSequentialGroup()
                .addGroup(jInventoryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInventoryDialogLayout.createSequentialGroup()
                        .addContainerGap(24, Short.MAX_VALUE)
                        .addComponent(jPlayerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInventoryDialogLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jInventoryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jItemInventoryLabel)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInventoryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane2))
                        .addGroup(jInventoryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInventoryDialogLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabelImageItem, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInventoryDialogLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jButtonSelectItemInventory)))
                        .addGap(41, 41, 41)))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("THE RUN: Quest");
        setName("jGameFrame"); // NOI18N

        jPanelExecute.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jCommandComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GO", "ELOPE", "SHOOT", "HIT", "USE", "TAKE", "THROW", "READ", "HELP" }));
        jCommandComboBox.setEnabled(false);
        jCommandComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCommandComboBoxActionPerformed(evt);
            }
        });

        jExecuteButton.setText("Execute");
        jExecuteButton.setEnabled(false);
        jExecuteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExecuteButtonActionPerformed(evt);
            }
        });

        jCommandLabel.setText("Command");

        javax.swing.GroupLayout jPanelExecuteLayout = new javax.swing.GroupLayout(jPanelExecute);
        jPanelExecute.setLayout(jPanelExecuteLayout);
        jPanelExecuteLayout.setHorizontalGroup(
            jPanelExecuteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExecuteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCommandLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCommandComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCommandTextField)
                .addGap(18, 18, 18)
                .addComponent(jExecuteButton)
                .addContainerGap())
        );
        jPanelExecuteLayout.setVerticalGroup(
            jPanelExecuteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExecuteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelExecuteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCommandComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jExecuteButton)
                    .addComponent(jCommandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCommandLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jNavigationPanel.setBorder(new javax.swing.border.MatteBorder(null));

        jStreetsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jStreetsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jStreetsListMouseClicked(evt);
            }
        });
        jStreetsScrollPane.setViewportView(jStreetsList);

        jLabelStreets.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStreets.setText("Streets:");

        javax.swing.GroupLayout jStreetsPanelLayout = new javax.swing.GroupLayout(jStreetsPanel);
        jStreetsPanel.setLayout(jStreetsPanelLayout);
        jStreetsPanelLayout.setHorizontalGroup(
            jStreetsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jStreetsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jStreetsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelStreets)
                    .addComponent(jStreetsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jStreetsPanelLayout.setVerticalGroup(
            jStreetsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jStreetsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelStreets)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jStreetsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelRooms.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelRooms.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelRooms.setText("Rooms:");

        jRoomsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRoomsListMouseClicked(evt);
            }
        });
        jRoomsScrollPane.setViewportView(jRoomsList);

        javax.swing.GroupLayout jPanelRoomsLayout = new javax.swing.GroupLayout(jPanelRooms);
        jPanelRooms.setLayout(jPanelRoomsLayout);
        jPanelRoomsLayout.setHorizontalGroup(
            jPanelRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRoomsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRoomsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRoomsLayout.setVerticalGroup(
            jPanelRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRoomsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRooms)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRoomsScrollPane)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jItemInvetoryInLocList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jItemInvetoryInLocListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jItemInvetoryInLocList);

        jItemsLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jItemsLabel.setText("Items in location:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jItemsLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jItemsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );

        jNPCPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMonsterList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMonsterListMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jMonsterList);

        jPlayerInfoFullLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPlayerInfoFullLabel.setText("Monsters:");

        jPeopleList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPeopleListMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jPeopleList);

        jPlayerInfoFullLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPlayerInfoFullLabel2.setText("People:");

        javax.swing.GroupLayout jNPCPanelLayout = new javax.swing.GroupLayout(jNPCPanel);
        jNPCPanel.setLayout(jNPCPanelLayout);
        jNPCPanelLayout.setHorizontalGroup(
            jNPCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNPCPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jNPCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPlayerInfoFullLabel)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(jPlayerInfoFullLabel2)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jNPCPanelLayout.setVerticalGroup(
            jNPCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNPCPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPlayerInfoFullLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPlayerInfoFullLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jNavigationPanelLayout = new javax.swing.GroupLayout(jNavigationPanel);
        jNavigationPanel.setLayout(jNavigationPanelLayout);
        jNavigationPanelLayout.setHorizontalGroup(
            jNavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNavigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jNavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jStreetsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelRooms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jNavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNPCPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jNavigationPanelLayout.setVerticalGroup(
            jNavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNavigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jNavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jStreetsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jNavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRooms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNPCPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jResultPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jResultLabel.setText("Result:");

        jResultTextField.setEditable(false);
        jResultTextField.setForeground(new java.awt.Color(0, 0, 255));

        jTurnLabel.setText("Turn:");

        jTurnTextField.setEditable(false);

        javax.swing.GroupLayout jResultPanelLayout = new javax.swing.GroupLayout(jResultPanel);
        jResultPanel.setLayout(jResultPanelLayout);
        jResultPanelLayout.setHorizontalGroup(
            jResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTurnLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTurnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jResultLabel)
                .addGap(18, 18, 18)
                .addComponent(jResultTextField)
                .addContainerGap())
        );
        jResultPanelLayout.setVerticalGroup(
            jResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jResultLabel)
                    .addComponent(jResultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTurnLabel)
                    .addComponent(jTurnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLocationInfoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLocationDescriptionTextArea.setEditable(false);
        jLocationDescriptionTextArea.setColumns(20);
        jLocationDescriptionTextArea.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLocationDescriptionTextArea.setLineWrap(true);
        jLocationDescriptionTextArea.setRows(5);
        jLocationInfoScrollPane.setViewportView(jLocationDescriptionTextArea);

        jInventoryButton.setText("Inventory");
        jInventoryButton.setEnabled(false);
        jInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInventoryButtonActionPerformed(evt);
            }
        });

        jHelpButton.setText("Help");
        jHelpButton.setEnabled(false);

        javax.swing.GroupLayout jLocationInfoPanelLayout = new javax.swing.GroupLayout(jLocationInfoPanel);
        jLocationInfoPanel.setLayout(jLocationInfoPanelLayout);
        jLocationInfoPanelLayout.setHorizontalGroup(
            jLocationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLocationInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLocationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jImageLocationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLocationInfoScrollPane)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLocationInfoPanelLayout.createSequentialGroup()
                        .addComponent(jInventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jHelpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jLocationInfoPanelLayout.setVerticalGroup(
            jLocationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLocationInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jImageLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLocationInfoScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jLocationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInventoryButton)
                    .addComponent(jHelpButton))
                .addContainerGap())
        );

        jGameMenuBar.setToolTipText("");
        jGameMenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jGameMenuBar.setName(""); // NOI18N

        GameJMenu.setText("Game");

        jStartMenuItem.setText("New Game");
        jStartMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStartMenuItemActionPerformed(evt);
            }
        });
        GameJMenu.add(jStartMenuItem);

        jStatsMenuItem.setText("Statistics");
        GameJMenu.add(jStatsMenuItem);

        jExitMenuItem.setText("Exit");
        jExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitMenuItemActionPerformed(evt);
            }
        });
        GameJMenu.add(jExitMenuItem);

        jGameMenuBar.add(GameJMenu);

        setJMenuBar(jGameMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jResultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLocationInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jNavigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 43, Short.MAX_VALUE))
                    .addComponent(jPanelExecute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNavigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLocationInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jResultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelExecute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jExitMenuItemActionPerformed

    private void jStartMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStartMenuItemActionPerformed
        // TODO add your handling code here:
        this.startGame();
    }//GEN-LAST:event_jStartMenuItemActionPerformed

    private void jStreetsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jStreetsListMouseClicked
        // TODO add your handling code here:
        jCommandTextField.setText((String) jStreetsList.getModel().getElementAt(jStreetsList.locationToIndex(evt.getPoint())));
    }//GEN-LAST:event_jStreetsListMouseClicked

    private void jExecuteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExecuteButtonActionPerformed
        // TODO add your handling code here:
        this.gController.execute(String.valueOf(jCommandComboBox.getSelectedItem()) + SEPARATOR + jCommandTextField.getText());
        jResultTextField.setText(this.gController.getProxyText().getResultMessage());
        jCommandTextField.setText("");
        this.initAllData();
        this.jTurnTextField.setText(String.valueOf(this.gController.getGameContext().getTurn()));
        this.gController.isGameOver();
        this.checkEvent();
    }//GEN-LAST:event_jExecuteButtonActionPerformed

    private void jCommandComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCommandComboBoxActionPerformed
        // TODO add your handling code here:
        //jCommandTextField.setText(String.valueOf(jCommandComboBox.getSelectedItem()));
    }//GEN-LAST:event_jCommandComboBoxActionPerformed

    private void jRoomsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRoomsListMouseClicked
        // TODO add your handling code here:
        jCommandTextField.setText((String) jRoomsList.getModel().getElementAt(jRoomsList.locationToIndex(evt.getPoint())));
    }//GEN-LAST:event_jRoomsListMouseClicked

    private void jInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInventoryButtonActionPerformed
        // TODO add your handling code here:
        jInventoryDialog.setLocationRelativeTo(null);
        jInventoryDialog.setVisible(true);
    }//GEN-LAST:event_jInventoryButtonActionPerformed

    private void jItemInvetoryInLocListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jItemInvetoryInLocListMouseClicked
        // TODO add your handling code here:
        ItemWrapper item = (ItemWrapper) jItemInvetoryInLocList.getModel().getElementAt(jItemInvetoryInLocList.locationToIndex(evt.getPoint()));
        jCommandTextField.setText(item.getName());
    }//GEN-LAST:event_jItemInvetoryInLocListMouseClicked

    private void jMonsterListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMonsterListMouseClicked
        // TODO add your handling code here:
       /* jCommandTextField.setText(jCommandTextField.getText() + SEPARATOR
         + jMonsterList.getModel().getElementAt(jMonsterList.locationToIndex(evt.getPoint())));*/
    }//GEN-LAST:event_jMonsterListMouseClicked

    private void jPeopleListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPeopleListMouseClicked
        // TODO add your handling code here:
        NPCWrapper npc = (NPCWrapper) jPeopleList.getModel().getElementAt(jPeopleList.locationToIndex(evt.getPoint()));
        jCommandTextField.setText(npc.getName());
    }//GEN-LAST:event_jPeopleListMouseClicked

    private void jInventoryPlayerListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInventoryPlayerListMouseClicked
        // TODO add your handling code here:
        ItemWrapper item = (ItemWrapper) jInventoryPlayerList.getModel()
                .getElementAt(jInventoryPlayerList.locationToIndex(evt.getPoint()));
        if (item.getDescription() != null && item.getImage() != null) {
            jLabelImageItem.setIcon(new javax.swing.ImageIcon(getClass().getResource(item.getImage())));
            jTextAreaItemDescription.setText(item.getDescription());
        }
    }//GEN-LAST:event_jInventoryPlayerListMouseClicked

    private void jButtonSelectItemInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectItemInventoryActionPerformed
        // TODO add your handling code here:
        ItemWrapper item = (ItemWrapper) jInventoryPlayerList.getSelectedValue();
        if (item != null) {
            jCommandTextField.setText(item.getName());
        }
    }//GEN-LAST:event_jButtonSelectItemInventoryActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GameUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu GameJMenu;
    private javax.swing.JButton jButtonSelectItemInventory;
    private javax.swing.JComboBox jCommandComboBox;
    private javax.swing.JLabel jCommandLabel;
    private javax.swing.JTextField jCommandTextField;
    private javax.swing.JButton jExecuteButton;
    private javax.swing.JMenuItem jExitMenuItem;
    private javax.swing.JMenuBar jGameMenuBar;
    private javax.swing.JLabel jHealthLabel;
    private javax.swing.JProgressBar jHealthProgressBar;
    private javax.swing.JButton jHelpButton;
    private javax.swing.JLabel jImageLocationLabel;
    private javax.swing.JLabel jImagePlayerLabel;
    private javax.swing.JButton jInventoryButton;
    private javax.swing.JDialog jInventoryDialog;
    private javax.swing.JList jInventoryPlayerList;
    private javax.swing.JLabel jItemInventoryLabel;
    private javax.swing.JList jItemInvetoryInLocList;
    private javax.swing.JLabel jItemsLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelImageItem;
    private javax.swing.JLabel jLabelRooms;
    private javax.swing.JLabel jLabelStreets;
    private javax.swing.JTextArea jLocationDescriptionTextArea;
    private javax.swing.JPanel jLocationInfoPanel;
    private javax.swing.JScrollPane jLocationInfoScrollPane;
    private javax.swing.JLabel jMStateLabel;
    private javax.swing.JProgressBar jMentalStateProgressBar;
    private javax.swing.JList jMonsterList;
    private javax.swing.JPanel jNPCPanel;
    private javax.swing.JLabel jNameLabel;
    private javax.swing.JPanel jNavigationPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelExecute;
    private javax.swing.JPanel jPanelRooms;
    private javax.swing.JList jPeopleList;
    private javax.swing.JLabel jPlayerInfoFullLabel;
    private javax.swing.JLabel jPlayerInfoFullLabel1;
    private javax.swing.JLabel jPlayerInfoFullLabel2;
    private javax.swing.JTextField jPlayerNameTextField;
    private javax.swing.JPanel jPlayerPanel;
    private javax.swing.JLabel jResultLabel;
    private javax.swing.JPanel jResultPanel;
    private javax.swing.JTextField jResultTextField;
    private javax.swing.JList jRoomsList;
    private javax.swing.JScrollPane jRoomsScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JMenuItem jStartMenuItem;
    private javax.swing.JMenuItem jStatsMenuItem;
    private javax.swing.JList jStreetsList;
    private javax.swing.JPanel jStreetsPanel;
    private javax.swing.JScrollPane jStreetsScrollPane;
    private javax.swing.JTextArea jTextAreaItemDescription;
    private javax.swing.JLabel jTurnLabel;
    private javax.swing.JTextField jTurnTextField;
    // End of variables declaration//GEN-END:variables
}
